vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       pro_picture:
           uri_prefix: /images/pro
           upload_destination: '%kernel.project_dir%/public/images/pro'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    
